spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/apidb"
    username: "apiuser"
    password: "apipass"
logging:
  level:
    com.example.blog.repository: DEBUG
    org.springframework.security: Trace
    org.springframework.data.redis: TRACE
    org.springframework.session: TRACE
server:
  servlet:
    session:
      timeout: 3600s # 実験用にとても短い30秒に設定